const item = (number,symbol,name,description,fred,unit,frequency,options={}) => ({number,symbol,name,description,fred,unit,frequency,kind:'series',decimals:2,...options});
export const MACRO_SERIES = [
  item(25,'MAC.CALENDAR','Economic Release Calendar','Upcoming BLS and BEA reports; historical graph counts scheduled releases per day.',null,'releases','Event schedule',{kind:'calendar',decimals:0}),
  item(null,'UST.2Y','2-Year Treasury Yield','Daily yield for the 2-year Treasury constant maturity.','DGS2','% yield','Daily',{decimals:3,source:'U.S. Treasury / FRED'}),
  item(null,'UST.10Y','10-Year Treasury Yield','Daily yield for the 10-year Treasury constant maturity.','DGS10','% yield','Daily',{decimals:3,source:'U.S. Treasury / FRED'}),
  item(null,'UST.30Y','30-Year Treasury Yield','Daily yield for the 30-year Treasury constant maturity.','DGS30','% yield','Daily',{decimals:3,source:'U.S. Treasury / FRED'}),
  item(11,'MAC.GDP','Real GDP Growth','Inflation-adjusted quarterly economic growth, expressed at an annual rate.','A191RL1Q225SBEA','% annualized','Quarterly',{source:'BEA / FRED'}),
  item(1,'MAC.CPI','Consumer Price Inflation','Annual change in household prices, including food and energy.','CPIAUCSL','% YoY','Monthly',{transform:'yoy',source:'BLS / FRED'}),
  item(3,'MAC.PCE','PCE Inflation','Annual change in consumer prices using the Fed’s target inflation measure.','PCEPI','% YoY','Monthly',{transform:'yoy',source:'BEA / FRED'}),
  item(5,'MAC.PPI','Producer Price Inflation','Annual change in prices received by producers for final demand.','PPIFIS','% YoY','Monthly',{transform:'yoy',source:'BLS / FRED'}),
  item(2,'MAC.CORECPI','Core Consumer Inflation','Annual household price change excluding food and energy.','CPILFESL','% YoY','Monthly',{transform:'yoy',source:'BLS / FRED'}),
  item(4,'MAC.COREPCE','Core PCE Inflation','Annual PCE price change excluding food and energy.','PCEPILFE','% YoY','Monthly',{transform:'yoy',source:'BEA / FRED'}),
  item(null,'UST.1M','1-Month Treasury Bill','Daily 1-month Treasury constant-maturity yield, investment basis.','DGS1MO','% yield','Daily',{decimals:3,source:'U.S. Treasury / FRED'}),
  item(null,'UST.3M','3-Month Treasury Bill','Daily 3-month Treasury constant-maturity yield, investment basis.','DGS3MO','% yield','Daily',{decimals:3,source:'U.S. Treasury / FRED'}),
  item(null,'UST.6M','6-Month Treasury Bill','Daily 6-month Treasury constant-maturity yield, investment basis.','DGS6MO','% yield','Daily',{decimals:3,source:'U.S. Treasury / FRED'}),
  item(null,'UST.1Y','1-Year Treasury Bill','Daily 1-year Treasury constant-maturity yield, investment basis.','DGS1','% yield','Daily',{decimals:3,source:'U.S. Treasury / FRED'}),
  item(null,'UST.5Y','5-Year Treasury Yield','Daily yield for the 5-year Treasury constant maturity.','DGS5','% yield','Daily',{decimals:3,source:'U.S. Treasury / FRED'}),
  item(null,'UST.10-2','10-Year Minus 2-Year Spread','10-year yield minus 2-year yield; a negative value means an inverted curve.','T10Y2Y','% spread','Daily',{decimals:3,source:'U.S. Treasury / FRED'}),
  item(7,'MAC.JOBS','Nonfarm Payroll Change','Jobs added or lost since the previous month, in thousands.','PAYEMS','k jobs','Monthly',{transform:'diff',decimals:0,source:'BLS / FRED'}),
  item(6,'MAC.UNEMP','Unemployment Rate','Share of the labor force without a job and actively seeking work.','UNRATE','%','Monthly',{source:'BLS / FRED'}),
  item(10,'MAC.WAGES','Wage Growth','Annual change in average hourly earnings for private-sector employees.','CES0500000003','% YoY','Monthly',{transform:'yoy',source:'BLS / FRED'}),
  item(8,'MAC.CLAIMS','Initial Jobless Claims','New unemployment-benefit applications each week.','ICSA','k claims','Weekly',{scale:.001,decimals:0,source:'Department of Labor / FRED'}),
  item(9,'MAC.JOLTS','Job Openings','Unfilled positions employers are actively recruiting for.','JTSJOL','M jobs','Monthly',{scale:.001,source:'BLS / FRED'}),
  item(12,'MAC.RETAIL','Retail Sales Growth','Monthly change in dollar spending at retailers and restaurants.','RSAFS','% MoM','Monthly',{transform:'mom',source:'Census Bureau / FRED'}),
  item(13,'MAC.SPEND','Real Consumer Spending Growth','Monthly spending change after removing inflation, across goods and services.','PCEC96','% MoM','Monthly',{transform:'mom',source:'BEA / FRED'}),
  item(14,'MAC.INDPRO','Industrial Production','Output from factories, mines, and utilities; index, 2017 = 100.','INDPRO','index','Monthly',{source:'Federal Reserve / FRED'}),
  item(24,'MAC.SENT','Consumer Sentiment','University of Michigan household sentiment index; FRED publication is delayed.','UMCSENT','index','Monthly',{source:'University of Michigan / FRED',delayNote:'FRED publishes this series with a one-month delay.'}),
  item(15,'MAC.STARTS','Housing Starts','New homes whose construction began; annualized rate.','HOUST','M homes SAAR','Monthly',{scale:.001,source:'Census Bureau / FRED'}),
  item(16,'MAC.PERMITS','Building Permits','New homes authorized for construction; annualized rate.','PERMIT','M homes SAAR','Monthly',{scale:.001,source:'Census Bureau / FRED'}),
  item(17,'MAC.HOMES','Home Price Growth','Annual change in the Case-Shiller U.S. national home-price index.','CSUSHPINSA','% YoY','Monthly',{transform:'yoy',source:'S&P Cotality Case-Shiller / FRED'}),
  item(19,'MAC.FEDBS','Fed Balance Sheet','Total assets held by the Federal Reserve.','WALCL','$T','Weekly',{scale:.000001,source:'Federal Reserve / FRED'}),
  item(18,'MAC.M2','M2 Money Supply','Cash, deposits, and selected other readily accessible money balances.','M2SL','$T','Monthly',{scale:.001,source:'Federal Reserve / FRED'}),
  item(20,'MAC.LOANS','Bank Lending','Loans and leases outstanding at U.S. commercial banks.','TOTLL','$T','Weekly',{scale:.001,source:'Federal Reserve / FRED'}),
  item(21,'MAC.CREDIT','Corporate Credit Spread','Extra yield on high-yield corporate bonds over Treasuries, adjusted for options.','BAMLH0A0HYM2','% spread','Daily',{source:'ICE BofA / FRED'})
];
